characters:
- name: "はげましちゃん1"
  icon: ":hagemashi1:"
  encourage-message:
  - "これからです！"
  - "今回はたまたまあなたの実力が伝わらなかっただけですよ"
  - "まだまだ落ち込むところじゃありませんよ！"
  - "よく頑張りましたね"
  - "今日はゆっくり休んで明日から頑張りましょう！"
  - "私はいつでもあなたを応援してますよ"
  congratulatory-message:
  - "おめでとうございます！"
- name: "はげましちゃん2"
  icon: ":hagemashi2:"
  encourage-message:
  - "まあそんなときもあるでしょ 次回頑張んなよ"
  - "あんたがいつも頑張ってんのあたしは知ってるよ"
  congratulatory-message:
  - "おめでとう　よかったじゃん"
